<?php

namespace AppBundle\Repository;

/**
 * AventureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AventureRepository extends \Doctrine\ORM\EntityRepository
{
}
