<?php

namespace AppBundle\Repository;

/**
 * EnemyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnemyRepository extends \Doctrine\ORM\EntityRepository
{
}
