<?php

namespace AppBundle\Repository;

/**
 * FightingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightingRepository extends \Doctrine\ORM\EntityRepository
{
}
