<?php

namespace AppBundle\Repository;

/**
 * PreActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreActionRepository extends \Doctrine\ORM\EntityRepository
{
}
